//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtWork
    {
        public int fileID { get; set; }
        public string FileName { get; set; }
        public byte[] ArtworkThumbnail { get; set; }
        public byte[] ImageData { get; set; }
        public Nullable<int> CIGID { get; set; }
        public Nullable<short> SubComponentID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<long> ImageMimeType { get; set; }
        public string imagePath { get; set; }
    
        public virtual tbl_LK_FarmerCIG tbl_LK_FarmerCIG { get; set; }
        public virtual tbl_LK_ME_SubComponent tbl_LK_ME_SubComponent { get; set; }
        public virtual tbl_LK_State tbl_LK_State { get; set; }
    }
}
