//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CADPEntities : DbContext
    {
        public CADPEntities()
            : base("name=CADPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArtWork> ArtWorks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_FarmAcquaculture> tbl_FarmAcquaculture { get; set; }
        public virtual DbSet<TBL_FarmPoulty> TBL_FarmPoulty { get; set; }
        public virtual DbSet<tbl_LK_FarmActivity> tbl_LK_FarmActivity { get; set; }
        public virtual DbSet<tbl_LK_Farmer> tbl_LK_Farmer { get; set; }
        public virtual DbSet<tbl_LK_FarmerBenefit> tbl_LK_FarmerBenefit { get; set; }
        public virtual DbSet<tbl_LK_FarmerCIG> tbl_LK_FarmerCIG { get; set; }
        public virtual DbSet<tbl_LK_FarmerProduction> tbl_LK_FarmerProduction { get; set; }
        public virtual DbSet<tbl_LK_FarmerProductionSeason> tbl_LK_FarmerProductionSeason { get; set; }
        public virtual DbSet<tbl_LK_FarmList> tbl_LK_FarmList { get; set; }
        public virtual DbSet<tbl_LK_FarmProduct> tbl_LK_FarmProduct { get; set; }
        public virtual DbSet<tbl_LK_FarmSize> tbl_LK_FarmSize { get; set; }
        public virtual DbSet<tbl_LK_FarmValueChain> tbl_LK_FarmValueChain { get; set; }
        public virtual DbSet<tbl_LK_Group_type> tbl_LK_Group_type { get; set; }
        public virtual DbSet<tbl_LK_Lga> tbl_LK_Lga { get; set; }
        public virtual DbSet<tbl_LK_Marketer> tbl_LK_Marketer { get; set; }
        public virtual DbSet<tbl_LK_MarketList> tbl_LK_MarketList { get; set; }
        public virtual DbSet<tbl_LK_MarketProduct> tbl_LK_MarketProduct { get; set; }
        public virtual DbSet<tbl_LK_MarketUnitOfMeaure> tbl_LK_MarketUnitOfMeaure { get; set; }
        public virtual DbSet<tbl_LK_ME_Component> tbl_LK_ME_Component { get; set; }
        public virtual DbSet<tbl_LK_ME_Indicator> tbl_LK_ME_Indicator { get; set; }
        public virtual DbSet<tbl_LK_ME_SubComponent> tbl_LK_ME_SubComponent { get; set; }
        public virtual DbSet<tbl_LK_OfferTypes> tbl_LK_OfferTypes { get; set; }
        public virtual DbSet<tbl_LK_State> tbl_LK_State { get; set; }
        public virtual DbSet<tbl_LK_Year> tbl_LK_Year { get; set; }
        public virtual DbSet<tbl_MarketInformation> tbl_MarketInformation { get; set; }
        public virtual DbSet<tbl_MarketPrice> tbl_MarketPrice { get; set; }
        public virtual DbSet<tbl_ME_Baseline> tbl_ME_Baseline { get; set; }
        public virtual DbSet<tbl_ME_LK_IndicatorRegister> tbl_ME_LK_IndicatorRegister { get; set; }
        public virtual DbSet<tbl_ME_RegisterIndicatorAchievement> tbl_ME_RegisterIndicatorAchievement { get; set; }
        public virtual DbSet<tbl_ME_RegisterIndicatorTarget> tbl_ME_RegisterIndicatorTarget { get; set; }
        public virtual DbSet<tbl_MktOfficer> tbl_MktOfficer { get; set; }
    }
}
