//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MktOfficer
    {
        public tbl_MktOfficer()
        {
            this.tbl_MarketPrice = new HashSet<tbl_MarketPrice>();
        }
    
        public int MarketOfficerID { get; set; }
        public string OfficersName { get; set; }
        public Nullable<int> MarketListID { get; set; }
    
        public virtual ICollection<tbl_MarketPrice> tbl_MarketPrice { get; set; }
    }
}
