//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LK_FarmerProductionSeason
    {
        public tbl_LK_FarmerProductionSeason()
        {
            this.tbl_FarmAcquaculture = new HashSet<tbl_FarmAcquaculture>();
            this.TBL_FarmPoulty = new HashSet<TBL_FarmPoulty>();
            this.tbl_LK_FarmerBenefit = new HashSet<tbl_LK_FarmerBenefit>();
            this.tbl_LK_FarmerProduction = new HashSet<tbl_LK_FarmerProduction>();
            this.tbl_ME_RegisterIndicatorAchievement = new HashSet<tbl_ME_RegisterIndicatorAchievement>();
            this.tbl_ME_RegisterIndicatorTarget = new HashSet<tbl_ME_RegisterIndicatorTarget>();
        }
    
        public int ProductionSeasonID { get; set; }
        public string ProductionSeasonName { get; set; }
    
        public virtual ICollection<tbl_FarmAcquaculture> tbl_FarmAcquaculture { get; set; }
        public virtual ICollection<TBL_FarmPoulty> TBL_FarmPoulty { get; set; }
        public virtual ICollection<tbl_LK_FarmerBenefit> tbl_LK_FarmerBenefit { get; set; }
        public virtual ICollection<tbl_LK_FarmerProduction> tbl_LK_FarmerProduction { get; set; }
        public virtual ICollection<tbl_ME_RegisterIndicatorAchievement> tbl_ME_RegisterIndicatorAchievement { get; set; }
        public virtual ICollection<tbl_ME_RegisterIndicatorTarget> tbl_ME_RegisterIndicatorTarget { get; set; }
    }
}
