//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LK_ME_Indicator
    {
        public tbl_LK_ME_Indicator()
        {
            this.tbl_ME_LK_IndicatorRegister = new HashSet<tbl_ME_LK_IndicatorRegister>();
        }
    
        public int IndicatorsID { get; set; }
        public Nullable<short> SubComponentID { get; set; }
        public string IndicatorName { get; set; }
        public Nullable<bool> Summable { get; set; }
    
        public virtual tbl_LK_ME_SubComponent tbl_LK_ME_SubComponent { get; set; }
        public virtual ICollection<tbl_ME_LK_IndicatorRegister> tbl_ME_LK_IndicatorRegister { get; set; }
    }
}
