//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LK_State
    {
        public tbl_LK_State()
        {
            this.ArtWorks = new HashSet<ArtWork>();
            this.tbl_LK_Farmer = new HashSet<tbl_LK_Farmer>();
            this.tbl_LK_FarmerBenefit = new HashSet<tbl_LK_FarmerBenefit>();
            this.tbl_LK_FarmerCIG = new HashSet<tbl_LK_FarmerCIG>();
            this.tbl_LK_FarmerProduction = new HashSet<tbl_LK_FarmerProduction>();
            this.tbl_LK_Lga = new HashSet<tbl_LK_Lga>();
            this.tbl_LK_Marketer = new HashSet<tbl_LK_Marketer>();
            this.tbl_LK_MarketList = new HashSet<tbl_LK_MarketList>();
            this.tbl_MarketInformation = new HashSet<tbl_MarketInformation>();
            this.tbl_MarketPrice = new HashSet<tbl_MarketPrice>();
            this.tbl_ME_Baseline = new HashSet<tbl_ME_Baseline>();
            this.tbl_ME_RegisterIndicatorTarget = new HashSet<tbl_ME_RegisterIndicatorTarget>();
        }
    
        public int StateID { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<ArtWork> ArtWorks { get; set; }
        public virtual ICollection<tbl_LK_Farmer> tbl_LK_Farmer { get; set; }
        public virtual ICollection<tbl_LK_FarmerBenefit> tbl_LK_FarmerBenefit { get; set; }
        public virtual ICollection<tbl_LK_FarmerCIG> tbl_LK_FarmerCIG { get; set; }
        public virtual ICollection<tbl_LK_FarmerProduction> tbl_LK_FarmerProduction { get; set; }
        public virtual ICollection<tbl_LK_Lga> tbl_LK_Lga { get; set; }
        public virtual ICollection<tbl_LK_Marketer> tbl_LK_Marketer { get; set; }
        public virtual ICollection<tbl_LK_MarketList> tbl_LK_MarketList { get; set; }
        public virtual ICollection<tbl_MarketInformation> tbl_MarketInformation { get; set; }
        public virtual ICollection<tbl_MarketPrice> tbl_MarketPrice { get; set; }
        public virtual ICollection<tbl_ME_Baseline> tbl_ME_Baseline { get; set; }
        public virtual ICollection<tbl_ME_RegisterIndicatorTarget> tbl_ME_RegisterIndicatorTarget { get; set; }
    }
}
