//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LK_FarmerCIG
    {
        public tbl_LK_FarmerCIG()
        {
            this.ArtWorks = new HashSet<ArtWork>();
            this.tbl_LK_Farmer = new HashSet<tbl_LK_Farmer>();
            this.tbl_LK_FarmerBenefit = new HashSet<tbl_LK_FarmerBenefit>();
            this.tbl_LK_FarmerProduction = new HashSet<tbl_LK_FarmerProduction>();
            this.tbl_ME_Baseline = new HashSet<tbl_ME_Baseline>();
            this.tbl_ME_RegisterIndicatorAchievement = new HashSet<tbl_ME_RegisterIndicatorAchievement>();
            this.tbl_ME_RegisterIndicatorTarget = new HashSet<tbl_ME_RegisterIndicatorTarget>();
        }
    
        public int CIGID { get; set; }
        public string CIGName { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<System.DateTime> dateIssued { get; set; }
        public Nullable<int> GroupTypeID { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ICollection<ArtWork> ArtWorks { get; set; }
        public virtual ICollection<tbl_LK_Farmer> tbl_LK_Farmer { get; set; }
        public virtual ICollection<tbl_LK_FarmerBenefit> tbl_LK_FarmerBenefit { get; set; }
        public virtual tbl_LK_Group_type tbl_LK_Group_type { get; set; }
        public virtual tbl_LK_State tbl_LK_State { get; set; }
        public virtual tbl_LK_Year tbl_LK_Year { get; set; }
        public virtual ICollection<tbl_LK_FarmerProduction> tbl_LK_FarmerProduction { get; set; }
        public virtual ICollection<tbl_ME_Baseline> tbl_ME_Baseline { get; set; }
        public virtual ICollection<tbl_ME_RegisterIndicatorAchievement> tbl_ME_RegisterIndicatorAchievement { get; set; }
        public virtual ICollection<tbl_ME_RegisterIndicatorTarget> tbl_ME_RegisterIndicatorTarget { get; set; }
    }
}
