//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LK_MarketProduct
    {
        public tbl_LK_MarketProduct()
        {
            this.tbl_MarketInformation = new HashSet<tbl_MarketInformation>();
            this.tbl_MarketPrice = new HashSet<tbl_MarketPrice>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int UnitOfMeasureID { get; set; }
    
        public virtual tbl_LK_MarketUnitOfMeaure tbl_LK_MarketUnitOfMeaure { get; set; }
        public virtual ICollection<tbl_MarketInformation> tbl_MarketInformation { get; set; }
        public virtual ICollection<tbl_MarketPrice> tbl_MarketPrice { get; set; }
    }
}
