//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LK_FarmerBenefit
    {
        public int FarmerBenefitID { get; set; }
        public Nullable<int> FarmerID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ProductionSeasonID { get; set; }
        public Nullable<System.DateTime> dateIssued { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CIGID { get; set; }
        public string Remark { get; set; }
    
        public virtual tbl_LK_Farmer tbl_LK_Farmer { get; set; }
        public virtual tbl_LK_FarmerCIG tbl_LK_FarmerCIG { get; set; }
        public virtual tbl_LK_FarmerProductionSeason tbl_LK_FarmerProductionSeason { get; set; }
        public virtual tbl_LK_State tbl_LK_State { get; set; }
    }
}
