//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LK_Year
    {
        public tbl_LK_Year()
        {
            this.tbl_LK_FarmerCIG = new HashSet<tbl_LK_FarmerCIG>();
            this.tbl_LK_FarmerProduction = new HashSet<tbl_LK_FarmerProduction>();
            this.tbl_ME_RegisterIndicatorAchievement = new HashSet<tbl_ME_RegisterIndicatorAchievement>();
            this.tbl_ME_RegisterIndicatorTarget = new HashSet<tbl_ME_RegisterIndicatorTarget>();
        }
    
        public int YearID { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ICollection<tbl_LK_FarmerCIG> tbl_LK_FarmerCIG { get; set; }
        public virtual ICollection<tbl_LK_FarmerProduction> tbl_LK_FarmerProduction { get; set; }
        public virtual ICollection<tbl_ME_RegisterIndicatorAchievement> tbl_ME_RegisterIndicatorAchievement { get; set; }
        public virtual ICollection<tbl_ME_RegisterIndicatorTarget> tbl_ME_RegisterIndicatorTarget { get; set; }
    }
}
