//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ME_Baseline
    {
        public int BaseLineID { get; set; }
        public Nullable<int> RegisterIndicatorsID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CIGID { get; set; }
        public Nullable<decimal> BaseData { get; set; }
    
        public virtual tbl_LK_FarmerCIG tbl_LK_FarmerCIG { get; set; }
        public virtual tbl_LK_State tbl_LK_State { get; set; }
        public virtual tbl_ME_LK_IndicatorRegister tbl_ME_LK_IndicatorRegister { get; set; }
    }
}
