//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LK_MarketList
    {
        public tbl_LK_MarketList()
        {
            this.tbl_LK_Marketer = new HashSet<tbl_LK_Marketer>();
            this.tbl_MarketInformation = new HashSet<tbl_MarketInformation>();
            this.tbl_MarketPrice = new HashSet<tbl_MarketPrice>();
        }
    
        public int MarketListID { get; set; }
        public string MarketListName { get; set; }
        public Nullable<int> StateID { get; set; }
        public int LgaID { get; set; }
        public string MarketAddres { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public string location { get; set; }
    
        public virtual tbl_LK_Lga tbl_LK_Lga { get; set; }
        public virtual ICollection<tbl_LK_Marketer> tbl_LK_Marketer { get; set; }
        public virtual tbl_LK_State tbl_LK_State { get; set; }
        public virtual ICollection<tbl_MarketInformation> tbl_MarketInformation { get; set; }
        public virtual ICollection<tbl_MarketPrice> tbl_MarketPrice { get; set; }
    }
}
