//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ME_LK_IndicatorRegister
    {
        public tbl_ME_LK_IndicatorRegister()
        {
            this.tbl_ME_Baseline = new HashSet<tbl_ME_Baseline>();
            this.tbl_ME_RegisterIndicatorAchievement = new HashSet<tbl_ME_RegisterIndicatorAchievement>();
            this.tbl_ME_RegisterIndicatorTarget = new HashSet<tbl_ME_RegisterIndicatorTarget>();
        }
    
        public int RegisterIndicatorsID { get; set; }
        public Nullable<int> IndicatorsID { get; set; }
        public Nullable<short> SubComponentID { get; set; }
        public string IndicatorName { get; set; }
        public Nullable<int> UnitOfMeasureID { get; set; }
        public Nullable<bool> Summable { get; set; }
        public string Remark { get; set; }
    
        public virtual tbl_LK_MarketUnitOfMeaure tbl_LK_MarketUnitOfMeaure { get; set; }
        public virtual tbl_LK_MarketUnitOfMeaure tbl_LK_MarketUnitOfMeaure1 { get; set; }
        public virtual tbl_LK_ME_Indicator tbl_LK_ME_Indicator { get; set; }
        public virtual tbl_LK_ME_SubComponent tbl_LK_ME_SubComponent { get; set; }
        public virtual tbl_LK_ME_SubComponent tbl_LK_ME_SubComponent1 { get; set; }
        public virtual ICollection<tbl_ME_Baseline> tbl_ME_Baseline { get; set; }
        public virtual ICollection<tbl_ME_RegisterIndicatorAchievement> tbl_ME_RegisterIndicatorAchievement { get; set; }
        public virtual ICollection<tbl_ME_RegisterIndicatorTarget> tbl_ME_RegisterIndicatorTarget { get; set; }
    }
}
