//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ME_RegisterIndicatorTarget
    {
        public int TargetID { get; set; }
        public Nullable<int> RegisterIndicatorsID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CIGID { get; set; }
        public Nullable<int> ProductionSeasonID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<decimal> TargetData { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Approved { get; set; }
    
        public virtual tbl_LK_FarmerCIG tbl_LK_FarmerCIG { get; set; }
        public virtual tbl_LK_FarmerProductionSeason tbl_LK_FarmerProductionSeason { get; set; }
        public virtual tbl_LK_State tbl_LK_State { get; set; }
        public virtual tbl_LK_Year tbl_LK_Year { get; set; }
        public virtual tbl_ME_LK_IndicatorRegister tbl_ME_LK_IndicatorRegister { get; set; }
    }
}
