//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MarketPrice
    {
        public int MarketPriceID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> DateOfPrice { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> MarketOfficerID { get; set; }
        public Nullable<int> PriceApprovalID { get; set; }
        public Nullable<int> MarketListID { get; set; }
        public Nullable<int> UnitOfMeasureID { get; set; }
        public Nullable<int> LgaID { get; set; }
        public Nullable<int> StateID { get; set; }
    
        public virtual tbl_LK_Lga tbl_LK_Lga { get; set; }
        public virtual tbl_LK_Marketer tbl_LK_Marketer { get; set; }
        public virtual tbl_LK_MarketList tbl_LK_MarketList { get; set; }
        public virtual tbl_LK_MarketProduct tbl_LK_MarketProduct { get; set; }
        public virtual tbl_LK_MarketUnitOfMeaure tbl_LK_MarketUnitOfMeaure { get; set; }
        public virtual tbl_LK_State tbl_LK_State { get; set; }
        public virtual tbl_MktOfficer tbl_MktOfficer { get; set; }
    }
}
