//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LK_MarketUnitOfMeaure
    {
        public tbl_LK_MarketUnitOfMeaure()
        {
            this.tbl_LK_FarmProduct = new HashSet<tbl_LK_FarmProduct>();
            this.tbl_LK_MarketProduct = new HashSet<tbl_LK_MarketProduct>();
            this.tbl_MarketInformation = new HashSet<tbl_MarketInformation>();
            this.tbl_MarketPrice = new HashSet<tbl_MarketPrice>();
            this.tbl_ME_LK_IndicatorRegister = new HashSet<tbl_ME_LK_IndicatorRegister>();
            this.tbl_ME_LK_IndicatorRegister1 = new HashSet<tbl_ME_LK_IndicatorRegister>();
        }
    
        public int UnitOfMeasureID { get; set; }
        public string UnitOfMeasureName { get; set; }
    
        public virtual ICollection<tbl_LK_FarmProduct> tbl_LK_FarmProduct { get; set; }
        public virtual ICollection<tbl_LK_MarketProduct> tbl_LK_MarketProduct { get; set; }
        public virtual ICollection<tbl_MarketInformation> tbl_MarketInformation { get; set; }
        public virtual ICollection<tbl_MarketPrice> tbl_MarketPrice { get; set; }
        public virtual ICollection<tbl_ME_LK_IndicatorRegister> tbl_ME_LK_IndicatorRegister { get; set; }
        public virtual ICollection<tbl_ME_LK_IndicatorRegister> tbl_ME_LK_IndicatorRegister1 { get; set; }
    }
}
