//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LK_Farmer
    {
        public tbl_LK_Farmer()
        {
            this.tbl_FarmAcquaculture = new HashSet<tbl_FarmAcquaculture>();
            this.TBL_FarmPoulty = new HashSet<TBL_FarmPoulty>();
            this.tbl_LK_FarmerBenefit = new HashSet<tbl_LK_FarmerBenefit>();
            this.tbl_LK_FarmerProduction = new HashSet<tbl_LK_FarmerProduction>();
        }
    
        public int FarmerID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CIGID { get; set; }
        public Nullable<int> ValueChainID { get; set; }
        public Nullable<int> FarmActivityID { get; set; }
        public Nullable<int> FarmProductID { get; set; }
        public string FarmerName { get; set; }
        public string MobileNo1 { get; set; }
        public string MobileNo2 { get; set; }
        public Nullable<bool> Sex { get; set; }
        public decimal BaseLine { get; set; }
        public Nullable<int> FarmSizeID { get; set; }
        public string FarmName { get; set; }
        public Nullable<int> FarmListID { get; set; }
    
        public virtual ICollection<tbl_FarmAcquaculture> tbl_FarmAcquaculture { get; set; }
        public virtual ICollection<TBL_FarmPoulty> TBL_FarmPoulty { get; set; }
        public virtual tbl_LK_FarmActivity tbl_LK_FarmActivity { get; set; }
        public virtual tbl_LK_FarmerCIG tbl_LK_FarmerCIG { get; set; }
        public virtual tbl_LK_FarmList tbl_LK_FarmList { get; set; }
        public virtual tbl_LK_FarmProduct tbl_LK_FarmProduct { get; set; }
        public virtual tbl_LK_FarmSize tbl_LK_FarmSize { get; set; }
        public virtual tbl_LK_FarmValueChain tbl_LK_FarmValueChain { get; set; }
        public virtual tbl_LK_State tbl_LK_State { get; set; }
        public virtual ICollection<tbl_LK_FarmerBenefit> tbl_LK_FarmerBenefit { get; set; }
        public virtual ICollection<tbl_LK_FarmerProduction> tbl_LK_FarmerProduction { get; set; }
    }
}
