//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LK_Group_type
    {
        public tbl_LK_Group_type()
        {
            this.tbl_LK_FarmerCIG = new HashSet<tbl_LK_FarmerCIG>();
        }
    
        public int GroupTypeID { get; set; }
        public string GroupTypeName { get; set; }
    
        public virtual ICollection<tbl_LK_FarmerCIG> tbl_LK_FarmerCIG { get; set; }
    }
}
