//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MarketInformation
    {
        public long MarketInfoID { get; set; }
        public Nullable<int> MarketListID { get; set; }
        public Nullable<int> MarketerID { get; set; }
        public int ProductID { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> QuantityForSale { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> AvalabilityStatus { get; set; }
        public Nullable<int> UnitOfMeasureID { get; set; }
        public Nullable<int> LgaID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> OfferID { get; set; }
    
        public virtual tbl_LK_Lga tbl_LK_Lga { get; set; }
        public virtual tbl_LK_Marketer tbl_LK_Marketer { get; set; }
        public virtual tbl_LK_MarketList tbl_LK_MarketList { get; set; }
        public virtual tbl_LK_MarketProduct tbl_LK_MarketProduct { get; set; }
        public virtual tbl_LK_MarketUnitOfMeaure tbl_LK_MarketUnitOfMeaure { get; set; }
        public virtual tbl_LK_OfferTypes tbl_LK_OfferTypes { get; set; }
        public virtual tbl_LK_State tbl_LK_State { get; set; }
    }
}
